// <auto-generated />
using System;
using ECommerce.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507072709_UpdateLookupsTables")]
    partial class UpdateLookupsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfProducts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountAmount")
                        .IsRequired()
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("DiscountType")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductVariantOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductVariantOptions");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.SKUProductVariantOptions", b =>
                {
                    b.Property<int>("SkuId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantOptionsId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantId1")
                        .HasColumnType("int");

                    b.HasKey("SkuId", "ProductVariantId", "ProductVariantOptionsId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("ProductVariantId1");

                    b.HasIndex("ProductVariantOptionsId");

                    b.ToTable("SKUProductVariantOptions");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Sku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Skus");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Sales.Lookups.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(7888),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(7891),
                            ModifiedBy = 0,
                            StatusName = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(7899),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(7900),
                            ModifiedBy = 0,
                            StatusName = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(7902),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(7903),
                            ModifiedBy = 0,
                            StatusName = "Shipped"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(7905),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(7905),
                            ModifiedBy = 0,
                            StatusName = "Delivered"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Sales.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Sales.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderItemNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SkuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("SkuId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SkuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("SkuId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Lookups.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8532),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8533),
                            ModifiedBy = 0,
                            Name = "Amman"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8537),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8538),
                            ModifiedBy = 0,
                            Name = "Zarqa"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8540),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8541),
                            ModifiedBy = 0,
                            Name = "Irbid"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8543),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8544),
                            ModifiedBy = 0,
                            Name = "Russeifa"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8546),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8547),
                            ModifiedBy = 0,
                            Name = "Sahab"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8549),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8549),
                            ModifiedBy = 0,
                            Name = "As-Salt"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8553),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8553),
                            ModifiedBy = 0,
                            Name = "Aqaba"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8555),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8556),
                            ModifiedBy = 0,
                            Name = "Madaba"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8558),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8559),
                            ModifiedBy = 0,
                            Name = "Jerash"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8561),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8562),
                            ModifiedBy = 0,
                            Name = "Ma'an"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8564),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8564),
                            ModifiedBy = 0,
                            Name = "Al-Mafraq"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8567),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8567),
                            ModifiedBy = 0,
                            Name = "Tafilah"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8569),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8570),
                            ModifiedBy = 0,
                            Name = "Ajloun"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8572),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8573),
                            ModifiedBy = 0,
                            Name = "Riyadh"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8575),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8575),
                            ModifiedBy = 0,
                            Name = "Jeddah"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8578),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8578),
                            ModifiedBy = 0,
                            Name = "Dubai"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8580),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8580),
                            ModifiedBy = 0,
                            Name = "Abu Dhabi"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Lookups.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8487),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8487),
                            ModifiedBy = 0,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8490),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8491),
                            ModifiedBy = 0,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8493),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8494),
                            ModifiedBy = 0,
                            Name = "Jordan"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Lookups.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8435),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8436),
                            ModifiedBy = 0,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8440),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 7, 7, 27, 8, 894, DateTimeKind.Utc).AddTicks(8441),
                            ModifiedBy = 0,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstNameAr")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstNameEn")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastNameAr")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastNameEn")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MiddleNameAr")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MiddleNameEn")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("SkuId")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkuId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductImage", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductVariant", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductVariantOptions", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.ProductVariant", "ProductVariant")
                        .WithMany("ProductVariantOptions")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.SKUProductVariantOptions", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Products.ProductVariant", null)
                        .WithMany("SKUJoinOptions")
                        .HasForeignKey("ProductVariantId1");

                    b.HasOne("ECommerce.Domain.Entities.Products.ProductVariantOptions", "ProductVariantOptions")
                        .WithMany()
                        .HasForeignKey("ProductVariantOptionsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Products.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("ProductVariantOptions");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Sku", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.Product", "Product")
                        .WithMany("Skus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Sales.Order", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Sales.Lookups.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Users.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("OrderStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Sales.OrderItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Sales.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Products.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Address", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.Lookups.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Users.Lookups.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("ECommerce.Domain.Entities.Users.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("ECommerce.Domain.Entities.Users.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Cart", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ECommerce.Domain.Entities.Users.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.CartItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Products.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Lookups.City", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.Lookups.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.Lookups.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Wishlist", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.User", "User")
                        .WithOne("Wishlist")
                        .HasForeignKey("ECommerce.Domain.Entities.Users.Wishlist", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.WishlistItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Users.Wishlist", "Wishlist")
                        .WithMany("WishlistItems")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sku");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");

                    b.Navigation("Skus");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductVariant", b =>
                {
                    b.Navigation("ProductVariantOptions");

                    b.Navigation("SKUJoinOptions");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Sales.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Lookups.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Wishlist")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Wishlist", b =>
                {
                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
