// <auto-generated />
using System;
using ECommerce.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506122903_AddLookupsTables")]
    partial class AddLookupsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("DefaultPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("DiscountType")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("EnDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductVariantOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductVariantOptions");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.SKUProductVariantOptions", b =>
                {
                    b.Property<int>("SkuId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantOptionsId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantId1")
                        .HasColumnType("int");

                    b.HasKey("SkuId", "ProductVariantId", "ProductVariantOptionsId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("ProductVariantId1");

                    b.HasIndex("ProductVariantOptionsId");

                    b.ToTable("SKUProductVariantOptions");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Sku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Skus");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Sales.Lookups.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(5876),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(5879),
                            ModifiedBy = 0,
                            StatusName = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(5886),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(5887),
                            ModifiedBy = 0,
                            StatusName = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(5889),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(5890),
                            ModifiedBy = 0,
                            StatusName = "Shipped"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(5891),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(5892),
                            ModifiedBy = 0,
                            StatusName = "Delivered"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Sales.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Sales.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SkuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("SkuId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SkuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("SkuId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Lookups.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8397),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8398),
                            ModifiedBy = 0,
                            Name = "Amman"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8401),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8402),
                            ModifiedBy = 0,
                            Name = "Zarqa"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8404),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8405),
                            ModifiedBy = 0,
                            Name = "Irbid"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8475),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8476),
                            ModifiedBy = 0,
                            Name = "Russeifa"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8478),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8479),
                            ModifiedBy = 0,
                            Name = "Sahab"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8481),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8481),
                            ModifiedBy = 0,
                            Name = "As-Salt"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8483),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8484),
                            ModifiedBy = 0,
                            Name = "Aqaba"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8486),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8486),
                            ModifiedBy = 0,
                            Name = "Madaba"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8488),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8489),
                            ModifiedBy = 0,
                            Name = "Jerash"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8490),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8491),
                            ModifiedBy = 0,
                            Name = "Ma'an"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8492),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8493),
                            ModifiedBy = 0,
                            Name = "Al-Mafraq"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8494),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8495),
                            ModifiedBy = 0,
                            Name = "Tafilah"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8496),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8497),
                            ModifiedBy = 0,
                            Name = "Ajloun"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8499),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8499),
                            ModifiedBy = 0,
                            Name = "Riyadh"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8501),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8502),
                            ModifiedBy = 0,
                            Name = "Jeddah"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 2,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8503),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8504),
                            ModifiedBy = 0,
                            Name = "Dubai"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 2,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8505),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8506),
                            ModifiedBy = 0,
                            Name = "Abu Dhabi"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Lookups.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8272),
                            CreatedBy = 0,
                            IsDeleted = false,
                            IsoCode = "SA",
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8273),
                            ModifiedBy = 0,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8281),
                            CreatedBy = 0,
                            IsDeleted = false,
                            IsoCode = "AE",
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8281),
                            ModifiedBy = 0,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8284),
                            CreatedBy = 0,
                            IsDeleted = false,
                            IsoCode = "JO",
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 542, DateTimeKind.Utc).AddTicks(8285),
                            ModifiedBy = 0,
                            Name = "Jordan"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Lookups.CountryCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CountryCode");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "+966",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6199),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6200),
                            ModifiedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "+962",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6202),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6202),
                            ModifiedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Code = "+971",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6204),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6204),
                            ModifiedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Code = "+20",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6206),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6206),
                            ModifiedBy = 0
                        },
                        new
                        {
                            Id = 5,
                            Code = "+1",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6208),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6208),
                            ModifiedBy = 0
                        },
                        new
                        {
                            Id = 6,
                            Code = "+44",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6209),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6210),
                            ModifiedBy = 0
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Lookups.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6251),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6252),
                            ModifiedBy = 0,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6254),
                            CreatedBy = 0,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 5, 6, 12, 29, 2, 536, DateTimeKind.Utc).AddTicks(6254),
                            ModifiedBy = 0,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ArFirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ArLastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ArMiddleName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryCodeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnFirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EnLastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EnMiddleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("Phone")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryCodeId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("SkuId")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkuId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductImage", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductVariant", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductVariantOptions", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.ProductVariant", "ProductVariant")
                        .WithMany("ProductVariantOptions")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.SKUProductVariantOptions", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Products.ProductVariant", null)
                        .WithMany("SKUJoinOptions")
                        .HasForeignKey("ProductVariantId1");

                    b.HasOne("ECommerce.Domain.Entities.Products.ProductVariantOptions", "ProductVariantOptions")
                        .WithMany()
                        .HasForeignKey("ProductVariantOptionsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Products.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("ProductVariantOptions");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Sku", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.Product", "Product")
                        .WithMany("Skus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Sales.Order", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Sales.Lookups.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Users.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("OrderStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Sales.OrderItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Sales.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Products.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Address", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("ECommerce.Domain.Entities.Users.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Cart", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ECommerce.Domain.Entities.Users.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.CartItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Products.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Lookups.City", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.Lookups.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.Lookups.CountryCode", "CountryCode")
                        .WithMany()
                        .HasForeignKey("CountryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Users.Lookups.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryCode");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Wishlist", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Users.User", "User")
                        .WithOne("Wishlist")
                        .HasForeignKey("ECommerce.Domain.Entities.Users.Wishlist", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.WishlistItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Products.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Users.Wishlist", "Wishlist")
                        .WithMany("WishlistItems")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sku");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");

                    b.Navigation("Skus");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Products.ProductVariant", b =>
                {
                    b.Navigation("ProductVariantOptions");

                    b.Navigation("SKUJoinOptions");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Sales.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Lookups.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Wishlist")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Users.Wishlist", b =>
                {
                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
